apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-fxoq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-docker-python-rhtap-three-component-scenarios-fxoq
    app.kubernetes.io/part-of: mc-three-scenarios
  name: devfile-docker-python-rhtap-three-component-scenarios-fxoq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-fxoq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-fxoq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-nhvx-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-fxoq@sha256:a7f716fb1dbb1624341f72bb2a0b003e6d4e1fd3aabf9ed880c30ec3ec17eb4a
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
