apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-fxoq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-nhvx-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-fxoq@sha256:a7f716fb1dbb1624341f72bb2a0b003e6d4e1fd3aabf9ed880c30ec3ec17eb4a
        name: my-python
        resources: {}
status: {}
